// Shared URL references for files in public. SVG component imports remain direct.
export const PUBLIC_ASSETS = {
  brand: {
    pillchatLogo: "/brand/pillchat-logo.svg",
  },
  icons: {
    answer: "/icons/answer.svg",
    archive: "/icons/archive.svg",
    bell: "/icons/bell.svg",
    bellColored: "/icons/bell-colored.svg",
    calendar: "/icons/calendar.svg",
    cameraMuted: "/icons/camera-muted.svg",
    checkCircle: "/icons/check-circle.svg",
    checkCircleFilled: "/icons/check-circle-filled.svg",
    checkCircleMuted: "/icons/check-circle-muted.svg",
    checkCircleOutline: "/icons/check-circle-outline.svg",
    chevronLeft: "/icons/chevron-left.svg",
    chevronLeftWhite: "/icons/chevron-left-white.svg",
    chevronRight: "/icons/chevron-right.svg",
    ellipsisHorizontal: "/icons/ellipsis-horizontal.svg",
    ellipsisVertical: "/icons/ellipsis-vertical.svg",
    eye: "/icons/eye.svg",
    eyeOff: "/icons/eye-off.svg",
    file: "/icons/file.svg",
    headset: "/icons/headset.svg",
    home: "/icons/home.svg",
    image: "/icons/image.svg",
    inputClear: "/icons/input-clear.svg",
    like: "/icons/like.svg",
    likeFilled: "/icons/like-filled.svg",
    likeMuted: "/icons/like-muted.svg",
    logout: "/icons/logout.svg",
    notice: "/icons/notice.svg",
    pharmCoin: "/icons/pharm-coin.svg",
    plusCircle: "/icons/plus-circle.svg",
    privacyPolicy: "/icons/privacy-policy.svg",
    question: "/icons/question.svg",
    questionBank: "/icons/question-bank.svg",
    questionBubble: "/icons/question-bubble.svg",
    questionBubbleMuted: "/icons/question-bubble-muted.svg",
    removeCircleGray: "/icons/remove-circle-gray.svg",
    removeCircleWhite: "/icons/remove-circle-white.svg",
    search: "/icons/search.svg",
    settings: "/icons/settings.svg",
    terms: "/icons/terms.svg",
    user: "/icons/user.svg",
    userInfo: "/icons/user-info.svg",
    userRemove: "/icons/user-remove.svg",
    userUpgrade: "/icons/user-upgrade.svg",
  },
  illustrations: {
    attendanceBadge: "/illustrations/attendance-badge.svg",
    badgePlaceholder: "/illustrations/badge-placeholder.svg",
    couponTicket: "/illustrations/coupon-ticket.svg",
    defaultProfile: "/illustrations/default-profile.svg",
    glasses: "/illustrations/glasses.svg",
    heartBubble: "/illustrations/heart-bubble.svg",
    person: "/illustrations/person.svg",
    pillLoaderSprite: "/illustrations/pill-loader-sprite.png",
  },
} as const;
