import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import { ReactNode, Suspense } from "react";
import Script from "next/script";
import "./styles/globals.css";
import Providers from "./providers";
import { TopRouteProgress } from "@/components/molecules";

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  minimumScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <Script id="block-zoom" strategy="beforeInteractive">{`
          (function () {
            function onWheel(e) {
              if (e.ctrlKey || e.metaKey) e.preventDefault();
            }

            function onKeyDown(e) {
              var key = (e.key || "").toLowerCase();
              var code = e.code || "";

              if (!(e.ctrlKey || e.metaKey)) return;

              if (
                key === "+" ||
                key === "-" ||
                key === "=" ||
                code === "NumpadAdd" ||
                code === "NumpadSubtract"
              ) {
                e.preventDefault();
              }
            }

            function onTouchMove(e) {
              if (e.touches && e.touches.length >= 2) e.preventDefault();
            }

            function block(e) {
              e.preventDefault();
            }

            window.addEventListener("wheel", onWheel, { passive: false, capture: true });
            window.addEventListener("keydown", onKeyDown, { capture: true });
            document.addEventListener("touchmove", onTouchMove, { passive: false, capture: true });
            document.addEventListener("gesturestart", block, { passive: false, capture: true });
            document.addEventListener("gesturechange", block, { passive: false, capture: true });
            document.addEventListener("gestureend", block, { passive: false, capture: true });
          })();
        `}</Script>
      </head>
      <body className={pretendard.className}>
        <Script
          src="https://developers.kakao.com/sdk/js/kakao.min.js"
          strategy="afterInteractive"
        />
        <Suspense fallback={null}>
          <TopRouteProgress />
        </Suspense>
        <div className="container mx-auto max-w-screen-sm">
          <Providers>
            <Suspense>{children}</Suspense>
          </Providers>
        </div>
      </body>
    </html>
  );
}