name: auto add assign

on:
  pull_request_target:
    types:
      - opened

permissions:
  pull-requests: write

jobs:
  auto-assign-author:
    name: auto add assign author
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: toshimaru/auto-author-assign@v2.1.1
